// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package application

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.Architecture, b.ko.Spec.Architecture) {
		delta.Add("Spec.Architecture", a.ko.Spec.Architecture, b.ko.Spec.Architecture)
	} else if a.ko.Spec.Architecture != nil && b.ko.Spec.Architecture != nil {
		if *a.ko.Spec.Architecture != *b.ko.Spec.Architecture {
			delta.Add("Spec.Architecture", a.ko.Spec.Architecture, b.ko.Spec.Architecture)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.AutoStartConfiguration, b.ko.Spec.AutoStartConfiguration) {
		delta.Add("Spec.AutoStartConfiguration", a.ko.Spec.AutoStartConfiguration, b.ko.Spec.AutoStartConfiguration)
	} else if a.ko.Spec.AutoStartConfiguration != nil && b.ko.Spec.AutoStartConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.AutoStartConfiguration.Enabled, b.ko.Spec.AutoStartConfiguration.Enabled) {
			delta.Add("Spec.AutoStartConfiguration.Enabled", a.ko.Spec.AutoStartConfiguration.Enabled, b.ko.Spec.AutoStartConfiguration.Enabled)
		} else if a.ko.Spec.AutoStartConfiguration.Enabled != nil && b.ko.Spec.AutoStartConfiguration.Enabled != nil {
			if *a.ko.Spec.AutoStartConfiguration.Enabled != *b.ko.Spec.AutoStartConfiguration.Enabled {
				delta.Add("Spec.AutoStartConfiguration.Enabled", a.ko.Spec.AutoStartConfiguration.Enabled, b.ko.Spec.AutoStartConfiguration.Enabled)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.AutoStopConfiguration, b.ko.Spec.AutoStopConfiguration) {
		delta.Add("Spec.AutoStopConfiguration", a.ko.Spec.AutoStopConfiguration, b.ko.Spec.AutoStopConfiguration)
	} else if a.ko.Spec.AutoStopConfiguration != nil && b.ko.Spec.AutoStopConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.AutoStopConfiguration.Enabled, b.ko.Spec.AutoStopConfiguration.Enabled) {
			delta.Add("Spec.AutoStopConfiguration.Enabled", a.ko.Spec.AutoStopConfiguration.Enabled, b.ko.Spec.AutoStopConfiguration.Enabled)
		} else if a.ko.Spec.AutoStopConfiguration.Enabled != nil && b.ko.Spec.AutoStopConfiguration.Enabled != nil {
			if *a.ko.Spec.AutoStopConfiguration.Enabled != *b.ko.Spec.AutoStopConfiguration.Enabled {
				delta.Add("Spec.AutoStopConfiguration.Enabled", a.ko.Spec.AutoStopConfiguration.Enabled, b.ko.Spec.AutoStopConfiguration.Enabled)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.AutoStopConfiguration.IdleTimeoutMinutes, b.ko.Spec.AutoStopConfiguration.IdleTimeoutMinutes) {
			delta.Add("Spec.AutoStopConfiguration.IdleTimeoutMinutes", a.ko.Spec.AutoStopConfiguration.IdleTimeoutMinutes, b.ko.Spec.AutoStopConfiguration.IdleTimeoutMinutes)
		} else if a.ko.Spec.AutoStopConfiguration.IdleTimeoutMinutes != nil && b.ko.Spec.AutoStopConfiguration.IdleTimeoutMinutes != nil {
			if *a.ko.Spec.AutoStopConfiguration.IdleTimeoutMinutes != *b.ko.Spec.AutoStopConfiguration.IdleTimeoutMinutes {
				delta.Add("Spec.AutoStopConfiguration.IdleTimeoutMinutes", a.ko.Spec.AutoStopConfiguration.IdleTimeoutMinutes, b.ko.Spec.AutoStopConfiguration.IdleTimeoutMinutes)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ClientToken, b.ko.Spec.ClientToken) {
		delta.Add("Spec.ClientToken", a.ko.Spec.ClientToken, b.ko.Spec.ClientToken)
	} else if a.ko.Spec.ClientToken != nil && b.ko.Spec.ClientToken != nil {
		if *a.ko.Spec.ClientToken != *b.ko.Spec.ClientToken {
			delta.Add("Spec.ClientToken", a.ko.Spec.ClientToken, b.ko.Spec.ClientToken)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DiskEncryptionConfiguration, b.ko.Spec.DiskEncryptionConfiguration) {
		delta.Add("Spec.DiskEncryptionConfiguration", a.ko.Spec.DiskEncryptionConfiguration, b.ko.Spec.DiskEncryptionConfiguration)
	} else if a.ko.Spec.DiskEncryptionConfiguration != nil && b.ko.Spec.DiskEncryptionConfiguration != nil {
		if len(a.ko.Spec.DiskEncryptionConfiguration.EncryptionContext) != len(b.ko.Spec.DiskEncryptionConfiguration.EncryptionContext) {
			delta.Add("Spec.DiskEncryptionConfiguration.EncryptionContext", a.ko.Spec.DiskEncryptionConfiguration.EncryptionContext, b.ko.Spec.DiskEncryptionConfiguration.EncryptionContext)
		} else if len(a.ko.Spec.DiskEncryptionConfiguration.EncryptionContext) > 0 {
			if !ackcompare.MapStringStringPEqual(a.ko.Spec.DiskEncryptionConfiguration.EncryptionContext, b.ko.Spec.DiskEncryptionConfiguration.EncryptionContext) {
				delta.Add("Spec.DiskEncryptionConfiguration.EncryptionContext", a.ko.Spec.DiskEncryptionConfiguration.EncryptionContext, b.ko.Spec.DiskEncryptionConfiguration.EncryptionContext)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.DiskEncryptionConfiguration.EncryptionKeyARN, b.ko.Spec.DiskEncryptionConfiguration.EncryptionKeyARN) {
			delta.Add("Spec.DiskEncryptionConfiguration.EncryptionKeyARN", a.ko.Spec.DiskEncryptionConfiguration.EncryptionKeyARN, b.ko.Spec.DiskEncryptionConfiguration.EncryptionKeyARN)
		} else if a.ko.Spec.DiskEncryptionConfiguration.EncryptionKeyARN != nil && b.ko.Spec.DiskEncryptionConfiguration.EncryptionKeyARN != nil {
			if *a.ko.Spec.DiskEncryptionConfiguration.EncryptionKeyARN != *b.ko.Spec.DiskEncryptionConfiguration.EncryptionKeyARN {
				delta.Add("Spec.DiskEncryptionConfiguration.EncryptionKeyARN", a.ko.Spec.DiskEncryptionConfiguration.EncryptionKeyARN, b.ko.Spec.DiskEncryptionConfiguration.EncryptionKeyARN)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.IdentityCenterConfiguration, b.ko.Spec.IdentityCenterConfiguration) {
		delta.Add("Spec.IdentityCenterConfiguration", a.ko.Spec.IdentityCenterConfiguration, b.ko.Spec.IdentityCenterConfiguration)
	} else if a.ko.Spec.IdentityCenterConfiguration != nil && b.ko.Spec.IdentityCenterConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.IdentityCenterConfiguration.IdentityCenterInstanceARN, b.ko.Spec.IdentityCenterConfiguration.IdentityCenterInstanceARN) {
			delta.Add("Spec.IdentityCenterConfiguration.IdentityCenterInstanceARN", a.ko.Spec.IdentityCenterConfiguration.IdentityCenterInstanceARN, b.ko.Spec.IdentityCenterConfiguration.IdentityCenterInstanceARN)
		} else if a.ko.Spec.IdentityCenterConfiguration.IdentityCenterInstanceARN != nil && b.ko.Spec.IdentityCenterConfiguration.IdentityCenterInstanceARN != nil {
			if *a.ko.Spec.IdentityCenterConfiguration.IdentityCenterInstanceARN != *b.ko.Spec.IdentityCenterConfiguration.IdentityCenterInstanceARN {
				delta.Add("Spec.IdentityCenterConfiguration.IdentityCenterInstanceARN", a.ko.Spec.IdentityCenterConfiguration.IdentityCenterInstanceARN, b.ko.Spec.IdentityCenterConfiguration.IdentityCenterInstanceARN)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.IdentityCenterConfiguration.UserBackgroundSessionsEnabled, b.ko.Spec.IdentityCenterConfiguration.UserBackgroundSessionsEnabled) {
			delta.Add("Spec.IdentityCenterConfiguration.UserBackgroundSessionsEnabled", a.ko.Spec.IdentityCenterConfiguration.UserBackgroundSessionsEnabled, b.ko.Spec.IdentityCenterConfiguration.UserBackgroundSessionsEnabled)
		} else if a.ko.Spec.IdentityCenterConfiguration.UserBackgroundSessionsEnabled != nil && b.ko.Spec.IdentityCenterConfiguration.UserBackgroundSessionsEnabled != nil {
			if *a.ko.Spec.IdentityCenterConfiguration.UserBackgroundSessionsEnabled != *b.ko.Spec.IdentityCenterConfiguration.UserBackgroundSessionsEnabled {
				delta.Add("Spec.IdentityCenterConfiguration.UserBackgroundSessionsEnabled", a.ko.Spec.IdentityCenterConfiguration.UserBackgroundSessionsEnabled, b.ko.Spec.IdentityCenterConfiguration.UserBackgroundSessionsEnabled)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ImageConfiguration, b.ko.Spec.ImageConfiguration) {
		delta.Add("Spec.ImageConfiguration", a.ko.Spec.ImageConfiguration, b.ko.Spec.ImageConfiguration)
	} else if a.ko.Spec.ImageConfiguration != nil && b.ko.Spec.ImageConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.ImageConfiguration.ImageURI, b.ko.Spec.ImageConfiguration.ImageURI) {
			delta.Add("Spec.ImageConfiguration.ImageURI", a.ko.Spec.ImageConfiguration.ImageURI, b.ko.Spec.ImageConfiguration.ImageURI)
		} else if a.ko.Spec.ImageConfiguration.ImageURI != nil && b.ko.Spec.ImageConfiguration.ImageURI != nil {
			if *a.ko.Spec.ImageConfiguration.ImageURI != *b.ko.Spec.ImageConfiguration.ImageURI {
				delta.Add("Spec.ImageConfiguration.ImageURI", a.ko.Spec.ImageConfiguration.ImageURI, b.ko.Spec.ImageConfiguration.ImageURI)
			}
		}
	}
	if len(a.ko.Spec.InitialCapacity) != len(b.ko.Spec.InitialCapacity) {
		delta.Add("Spec.InitialCapacity", a.ko.Spec.InitialCapacity, b.ko.Spec.InitialCapacity)
	} else if len(a.ko.Spec.InitialCapacity) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.InitialCapacity, b.ko.Spec.InitialCapacity) {
			delta.Add("Spec.InitialCapacity", a.ko.Spec.InitialCapacity, b.ko.Spec.InitialCapacity)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.InteractiveConfiguration, b.ko.Spec.InteractiveConfiguration) {
		delta.Add("Spec.InteractiveConfiguration", a.ko.Spec.InteractiveConfiguration, b.ko.Spec.InteractiveConfiguration)
	} else if a.ko.Spec.InteractiveConfiguration != nil && b.ko.Spec.InteractiveConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.InteractiveConfiguration.LivyEndpointEnabled, b.ko.Spec.InteractiveConfiguration.LivyEndpointEnabled) {
			delta.Add("Spec.InteractiveConfiguration.LivyEndpointEnabled", a.ko.Spec.InteractiveConfiguration.LivyEndpointEnabled, b.ko.Spec.InteractiveConfiguration.LivyEndpointEnabled)
		} else if a.ko.Spec.InteractiveConfiguration.LivyEndpointEnabled != nil && b.ko.Spec.InteractiveConfiguration.LivyEndpointEnabled != nil {
			if *a.ko.Spec.InteractiveConfiguration.LivyEndpointEnabled != *b.ko.Spec.InteractiveConfiguration.LivyEndpointEnabled {
				delta.Add("Spec.InteractiveConfiguration.LivyEndpointEnabled", a.ko.Spec.InteractiveConfiguration.LivyEndpointEnabled, b.ko.Spec.InteractiveConfiguration.LivyEndpointEnabled)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.InteractiveConfiguration.StudioEnabled, b.ko.Spec.InteractiveConfiguration.StudioEnabled) {
			delta.Add("Spec.InteractiveConfiguration.StudioEnabled", a.ko.Spec.InteractiveConfiguration.StudioEnabled, b.ko.Spec.InteractiveConfiguration.StudioEnabled)
		} else if a.ko.Spec.InteractiveConfiguration.StudioEnabled != nil && b.ko.Spec.InteractiveConfiguration.StudioEnabled != nil {
			if *a.ko.Spec.InteractiveConfiguration.StudioEnabled != *b.ko.Spec.InteractiveConfiguration.StudioEnabled {
				delta.Add("Spec.InteractiveConfiguration.StudioEnabled", a.ko.Spec.InteractiveConfiguration.StudioEnabled, b.ko.Spec.InteractiveConfiguration.StudioEnabled)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.JobLevelCostAllocationConfiguration, b.ko.Spec.JobLevelCostAllocationConfiguration) {
		delta.Add("Spec.JobLevelCostAllocationConfiguration", a.ko.Spec.JobLevelCostAllocationConfiguration, b.ko.Spec.JobLevelCostAllocationConfiguration)
	} else if a.ko.Spec.JobLevelCostAllocationConfiguration != nil && b.ko.Spec.JobLevelCostAllocationConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.JobLevelCostAllocationConfiguration.Enabled, b.ko.Spec.JobLevelCostAllocationConfiguration.Enabled) {
			delta.Add("Spec.JobLevelCostAllocationConfiguration.Enabled", a.ko.Spec.JobLevelCostAllocationConfiguration.Enabled, b.ko.Spec.JobLevelCostAllocationConfiguration.Enabled)
		} else if a.ko.Spec.JobLevelCostAllocationConfiguration.Enabled != nil && b.ko.Spec.JobLevelCostAllocationConfiguration.Enabled != nil {
			if *a.ko.Spec.JobLevelCostAllocationConfiguration.Enabled != *b.ko.Spec.JobLevelCostAllocationConfiguration.Enabled {
				delta.Add("Spec.JobLevelCostAllocationConfiguration.Enabled", a.ko.Spec.JobLevelCostAllocationConfiguration.Enabled, b.ko.Spec.JobLevelCostAllocationConfiguration.Enabled)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MaximumCapacity, b.ko.Spec.MaximumCapacity) {
		delta.Add("Spec.MaximumCapacity", a.ko.Spec.MaximumCapacity, b.ko.Spec.MaximumCapacity)
	} else if a.ko.Spec.MaximumCapacity != nil && b.ko.Spec.MaximumCapacity != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.MaximumCapacity.CPU, b.ko.Spec.MaximumCapacity.CPU) {
			delta.Add("Spec.MaximumCapacity.CPU", a.ko.Spec.MaximumCapacity.CPU, b.ko.Spec.MaximumCapacity.CPU)
		} else if a.ko.Spec.MaximumCapacity.CPU != nil && b.ko.Spec.MaximumCapacity.CPU != nil {
			if *a.ko.Spec.MaximumCapacity.CPU != *b.ko.Spec.MaximumCapacity.CPU {
				delta.Add("Spec.MaximumCapacity.CPU", a.ko.Spec.MaximumCapacity.CPU, b.ko.Spec.MaximumCapacity.CPU)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.MaximumCapacity.Disk, b.ko.Spec.MaximumCapacity.Disk) {
			delta.Add("Spec.MaximumCapacity.Disk", a.ko.Spec.MaximumCapacity.Disk, b.ko.Spec.MaximumCapacity.Disk)
		} else if a.ko.Spec.MaximumCapacity.Disk != nil && b.ko.Spec.MaximumCapacity.Disk != nil {
			if *a.ko.Spec.MaximumCapacity.Disk != *b.ko.Spec.MaximumCapacity.Disk {
				delta.Add("Spec.MaximumCapacity.Disk", a.ko.Spec.MaximumCapacity.Disk, b.ko.Spec.MaximumCapacity.Disk)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.MaximumCapacity.Memory, b.ko.Spec.MaximumCapacity.Memory) {
			delta.Add("Spec.MaximumCapacity.Memory", a.ko.Spec.MaximumCapacity.Memory, b.ko.Spec.MaximumCapacity.Memory)
		} else if a.ko.Spec.MaximumCapacity.Memory != nil && b.ko.Spec.MaximumCapacity.Memory != nil {
			if *a.ko.Spec.MaximumCapacity.Memory != *b.ko.Spec.MaximumCapacity.Memory {
				delta.Add("Spec.MaximumCapacity.Memory", a.ko.Spec.MaximumCapacity.Memory, b.ko.Spec.MaximumCapacity.Memory)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MonitoringConfiguration, b.ko.Spec.MonitoringConfiguration) {
		delta.Add("Spec.MonitoringConfiguration", a.ko.Spec.MonitoringConfiguration, b.ko.Spec.MonitoringConfiguration)
	} else if a.ko.Spec.MonitoringConfiguration != nil && b.ko.Spec.MonitoringConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration, b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration) {
			delta.Add("Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration", a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration, b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration)
		} else if a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration != nil && b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled, b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled) {
				delta.Add("Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled", a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled, b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled)
			} else if a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled != nil && b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled != nil {
				if *a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled != *b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled {
					delta.Add("Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled", a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled, b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.Enabled)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyARN, b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyARN) {
				delta.Add("Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyARN", a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyARN, b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyARN)
			} else if a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyARN != nil && b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyARN != nil {
				if *a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyARN != *b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyARN {
					delta.Add("Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyARN", a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyARN, b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.EncryptionKeyARN)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName, b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName) {
				delta.Add("Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName", a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName, b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName)
			} else if a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName != nil && b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName != nil {
				if *a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName != *b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName {
					delta.Add("Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName", a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName, b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogGroupName)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix, b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix) {
				delta.Add("Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix", a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix, b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix)
			} else if a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix != nil && b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix != nil {
				if *a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix != *b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix {
					delta.Add("Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix", a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix, b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogStreamNamePrefix)
				}
			}
			if len(a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogTypes) != len(b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogTypes) {
				delta.Add("Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogTypes", a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogTypes, b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogTypes)
			} else if len(a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogTypes) > 0 {
				if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogTypes, b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogTypes) {
					delta.Add("Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogTypes", a.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogTypes, b.ko.Spec.MonitoringConfiguration.CloudWatchLoggingConfiguration.LogTypes)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration, b.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration) {
			delta.Add("Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration", a.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration, b.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration)
		} else if a.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration != nil && b.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled, b.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled) {
				delta.Add("Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled", a.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled, b.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled)
			} else if a.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled != nil && b.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled != nil {
				if *a.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled != *b.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled {
					delta.Add("Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled", a.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled, b.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.Enabled)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyARN, b.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyARN) {
				delta.Add("Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyARN", a.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyARN, b.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyARN)
			} else if a.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyARN != nil && b.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyARN != nil {
				if *a.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyARN != *b.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyARN {
					delta.Add("Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyARN", a.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyARN, b.ko.Spec.MonitoringConfiguration.ManagedPersistenceMonitoringConfiguration.EncryptionKeyARN)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration, b.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration) {
			delta.Add("Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration", a.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration, b.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration)
		} else if a.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration != nil && b.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteURL, b.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteURL) {
				delta.Add("Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteURL", a.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteURL, b.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteURL)
			} else if a.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteURL != nil && b.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteURL != nil {
				if *a.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteURL != *b.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteURL {
					delta.Add("Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteURL", a.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteURL, b.ko.Spec.MonitoringConfiguration.PrometheusMonitoringConfiguration.RemoteWriteURL)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration, b.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration) {
			delta.Add("Spec.MonitoringConfiguration.S3MonitoringConfiguration", a.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration, b.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration)
		} else if a.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration != nil && b.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyARN, b.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyARN) {
				delta.Add("Spec.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyARN", a.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyARN, b.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyARN)
			} else if a.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyARN != nil && b.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyARN != nil {
				if *a.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyARN != *b.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyARN {
					delta.Add("Spec.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyARN", a.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyARN, b.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.EncryptionKeyARN)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.LogURI, b.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.LogURI) {
				delta.Add("Spec.MonitoringConfiguration.S3MonitoringConfiguration.LogURI", a.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.LogURI, b.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.LogURI)
			} else if a.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.LogURI != nil && b.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.LogURI != nil {
				if *a.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.LogURI != *b.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.LogURI {
					delta.Add("Spec.MonitoringConfiguration.S3MonitoringConfiguration.LogURI", a.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.LogURI, b.ko.Spec.MonitoringConfiguration.S3MonitoringConfiguration.LogURI)
				}
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.NetworkConfiguration, b.ko.Spec.NetworkConfiguration) {
		delta.Add("Spec.NetworkConfiguration", a.ko.Spec.NetworkConfiguration, b.ko.Spec.NetworkConfiguration)
	} else if a.ko.Spec.NetworkConfiguration != nil && b.ko.Spec.NetworkConfiguration != nil {
		if len(a.ko.Spec.NetworkConfiguration.SecurityGroupIDs) != len(b.ko.Spec.NetworkConfiguration.SecurityGroupIDs) {
			delta.Add("Spec.NetworkConfiguration.SecurityGroupIDs", a.ko.Spec.NetworkConfiguration.SecurityGroupIDs, b.ko.Spec.NetworkConfiguration.SecurityGroupIDs)
		} else if len(a.ko.Spec.NetworkConfiguration.SecurityGroupIDs) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.NetworkConfiguration.SecurityGroupIDs, b.ko.Spec.NetworkConfiguration.SecurityGroupIDs) {
				delta.Add("Spec.NetworkConfiguration.SecurityGroupIDs", a.ko.Spec.NetworkConfiguration.SecurityGroupIDs, b.ko.Spec.NetworkConfiguration.SecurityGroupIDs)
			}
		}
		if len(a.ko.Spec.NetworkConfiguration.SubnetIDs) != len(b.ko.Spec.NetworkConfiguration.SubnetIDs) {
			delta.Add("Spec.NetworkConfiguration.SubnetIDs", a.ko.Spec.NetworkConfiguration.SubnetIDs, b.ko.Spec.NetworkConfiguration.SubnetIDs)
		} else if len(a.ko.Spec.NetworkConfiguration.SubnetIDs) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.NetworkConfiguration.SubnetIDs, b.ko.Spec.NetworkConfiguration.SubnetIDs) {
				delta.Add("Spec.NetworkConfiguration.SubnetIDs", a.ko.Spec.NetworkConfiguration.SubnetIDs, b.ko.Spec.NetworkConfiguration.SubnetIDs)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ReleaseLabel, b.ko.Spec.ReleaseLabel) {
		delta.Add("Spec.ReleaseLabel", a.ko.Spec.ReleaseLabel, b.ko.Spec.ReleaseLabel)
	} else if a.ko.Spec.ReleaseLabel != nil && b.ko.Spec.ReleaseLabel != nil {
		if *a.ko.Spec.ReleaseLabel != *b.ko.Spec.ReleaseLabel {
			delta.Add("Spec.ReleaseLabel", a.ko.Spec.ReleaseLabel, b.ko.Spec.ReleaseLabel)
		}
	}
	if len(a.ko.Spec.RuntimeConfiguration) != len(b.ko.Spec.RuntimeConfiguration) {
		delta.Add("Spec.RuntimeConfiguration", a.ko.Spec.RuntimeConfiguration, b.ko.Spec.RuntimeConfiguration)
	} else if len(a.ko.Spec.RuntimeConfiguration) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.RuntimeConfiguration, b.ko.Spec.RuntimeConfiguration) {
			delta.Add("Spec.RuntimeConfiguration", a.ko.Spec.RuntimeConfiguration, b.ko.Spec.RuntimeConfiguration)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SchedulerConfiguration, b.ko.Spec.SchedulerConfiguration) {
		delta.Add("Spec.SchedulerConfiguration", a.ko.Spec.SchedulerConfiguration, b.ko.Spec.SchedulerConfiguration)
	} else if a.ko.Spec.SchedulerConfiguration != nil && b.ko.Spec.SchedulerConfiguration != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.SchedulerConfiguration.MaxConcurrentRuns, b.ko.Spec.SchedulerConfiguration.MaxConcurrentRuns) {
			delta.Add("Spec.SchedulerConfiguration.MaxConcurrentRuns", a.ko.Spec.SchedulerConfiguration.MaxConcurrentRuns, b.ko.Spec.SchedulerConfiguration.MaxConcurrentRuns)
		} else if a.ko.Spec.SchedulerConfiguration.MaxConcurrentRuns != nil && b.ko.Spec.SchedulerConfiguration.MaxConcurrentRuns != nil {
			if *a.ko.Spec.SchedulerConfiguration.MaxConcurrentRuns != *b.ko.Spec.SchedulerConfiguration.MaxConcurrentRuns {
				delta.Add("Spec.SchedulerConfiguration.MaxConcurrentRuns", a.ko.Spec.SchedulerConfiguration.MaxConcurrentRuns, b.ko.Spec.SchedulerConfiguration.MaxConcurrentRuns)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.SchedulerConfiguration.QueueTimeoutMinutes, b.ko.Spec.SchedulerConfiguration.QueueTimeoutMinutes) {
			delta.Add("Spec.SchedulerConfiguration.QueueTimeoutMinutes", a.ko.Spec.SchedulerConfiguration.QueueTimeoutMinutes, b.ko.Spec.SchedulerConfiguration.QueueTimeoutMinutes)
		} else if a.ko.Spec.SchedulerConfiguration.QueueTimeoutMinutes != nil && b.ko.Spec.SchedulerConfiguration.QueueTimeoutMinutes != nil {
			if *a.ko.Spec.SchedulerConfiguration.QueueTimeoutMinutes != *b.ko.Spec.SchedulerConfiguration.QueueTimeoutMinutes {
				delta.Add("Spec.SchedulerConfiguration.QueueTimeoutMinutes", a.ko.Spec.SchedulerConfiguration.QueueTimeoutMinutes, b.ko.Spec.SchedulerConfiguration.QueueTimeoutMinutes)
			}
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Type, b.ko.Spec.Type) {
		delta.Add("Spec.Type", a.ko.Spec.Type, b.ko.Spec.Type)
	} else if a.ko.Spec.Type != nil && b.ko.Spec.Type != nil {
		if *a.ko.Spec.Type != *b.ko.Spec.Type {
			delta.Add("Spec.Type", a.ko.Spec.Type, b.ko.Spec.Type)
		}
	}
	if len(a.ko.Spec.WorkerTypeSpecifications) != len(b.ko.Spec.WorkerTypeSpecifications) {
		delta.Add("Spec.WorkerTypeSpecifications", a.ko.Spec.WorkerTypeSpecifications, b.ko.Spec.WorkerTypeSpecifications)
	} else if len(a.ko.Spec.WorkerTypeSpecifications) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.WorkerTypeSpecifications, b.ko.Spec.WorkerTypeSpecifications) {
			delta.Add("Spec.WorkerTypeSpecifications", a.ko.Spec.WorkerTypeSpecifications, b.ko.Spec.WorkerTypeSpecifications)
		}
	}

	return delta
}
